---
- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Ensure hiredis is installed (Debian).
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ hiredis_packages }}"
  when: (hiredis_install_from_source == false) and (ansible_os_family == 'Debian')

- include: install-from-source.yml
  when: hiredis_install_from_source == true
